
Use a MarkDown file for this section:

# What does one need to do to use a module?
>import the module.
## Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.
>math module print("Round up ... ", math.ceil(2.6))

### What is a benefit of using Exception handling?
>test code and find erros
#### NumPy arrays are like what Python data type?
>Lists
##### What is one of the main benefits of using NumPy arrays.
>Fast
###### What is one of the main requirements about the 'dtype' of NumPy arrays?
>has to be same data type
###### Of the 10 uses of NumPy, name 2.
>numpy.repeat & numpy.random.choice
###### Name one of the other libraries we'll use with NumPy?
>pandas
##### What is the shape of NumPy arrays?
>the number of units along each dimension of the array
##### What is a Tensor?
>an array with 3+ dimensions
##### Name a reason why it's better using  NumPy for Data Analysis than using a Python List?
>faster, less memory
##### When creating an "empty" array, where do the elements come from?
>is random and depends on the state of the memory


In [10]:

# using Date Time
import datetime as dt

# Get Current Date and Time
a = dt.datetime.now()
print("Current Date and Time ...", a)
##Use the DateTime module to get Current Date and Time, and save it to a variable. 
print("Month ...", a.strftime("%B"))
###Then extract just the Full month name form that variable.

def dna( name, day = 'sunday' ): 
    # "This code below prints all info passed into this function"
    print("Name: ", name)
    print("Age ", day)


Current Date and Time ... 2023-02-19 12:22:22.136267
Month ... February


In [31]:
def dna( name, day = "sunday"): 
    # "This code below prints all info passed into this function"
     print("Name: ", name)
     print("day ", day)
     print("hi",name,"happy",day)
##Have the function print out a greeting -- using the parameters -- that says something like "Hi first-name! Happy day-name!". Remember to use the variables in the greeting to replace first-name and day-name.

dna('joe',"sunday")


dna('joe')
dna('kyle','Monday')

#Invoke this function with 2 variables.
#Invoke this function with 1 variable only.


Name:  joe
day  sunday
hi joe happy sunday
Name:  joe
day  sunday
hi joe happy sunday
Name:  kyle
day  Monday
hi kyle happy Monday


In [1]:


import numpy
#Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2).
npdna = numpy.array([2, 3, 2,])
print(npdna)
#Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20


array = numpy.linspace(0, 20, 6)
print(array)

#Make a Deep Copy of the above array you created.
import copy

xarray=copy.deepcopy(array)
print(xarray)

#What are 2 reasons we use NumPy arrays over Python Lists
#1.faster and more compact 
#2.Uses less memory 

[2 3 2]
[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]
