
### 1.What does Pandas stand for?
>Panel Data” and “Python Data Analysis”
### 2.What are the 2 collections used in Pandas?
>Series and dqtq frame
### 3.Name 4 things Pandas can do for us.
>load, manipulate, prepare, model, and analyze data
### 4.To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
>Set the inplace parameter to True.
### 5.What is a CSV
>(comma separated files)CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
### 6.When cleaning data what values do we not like in our data?
>Null

In [7]:
#Concatenate these 3 arrays into a new array named 'newArray'...

import numpy
newArray = numpy.concatenate(([[25, 16]], [[11, 2], [13, 4]], [[7, 81], [5, 6], [11, 12]]))

#concatenate the arrays

print (newArray)

#Sort 'newArray' in order into 'sortedArray'

asortedArray = numpy.sort(newArray, axis=0)

print ("\n2:Sort 'newArray' in order into 'sortedArray'\n",asortedArray)

#Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = newArray.reshape(2, 3, 2)
print("\n reshaping bArray ...\n", reshapedArray)

#Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.


a, b, = reshapedArray

print("a = ", a + b)










[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

2:Sort 'newArray' in order into 'sortedArray'
 [[ 5  2]
 [ 7  4]
 [11  6]
 [11 12]
 [13 16]
 [25 81]]

 reshaping bArray ...
 [[[25 16]
  [11  2]
  [13  4]]

 [[ 7 81]
  [ 5  6]
  [11 12]]]
a =  [[32 97]
 [16  8]
 [24 16]]
b =  [[ 7 81]
 [ 5  6]
 [11 12]]


In [ ]:
#define arrays 
one = [10, 11, 12, 13, 14, 15, 16, 17]
two = [20, 21, 22, 23, 24, 25, 26, 27]
three = [0, 1, 2, 3, 4, 5, 6, 7]

#combine arrays 

comboArray = numpy.concatenate((one, two, three))
#sort arrays
sortedComboArray = numpy.sort(comboArray)

print("5:Combined and sort the following arrays into one\n",sortedComboArray)


# Print sec1 - the 2nd element
sec1 = comboArray[1]
print("sec1:", sec1)

# Print sec2 - all elements from the 3rd element to the last
sec2 = comboArray[2:]
print("sec2:", sec2)

# Print sec3 - all elements from the 4th to the 14th elements
sec3 = comboArray[3:14]
print("sec3:", sec3)

# Print sec4 - the last 6 elements
sec4 = comboArray[-6:]
print("sec4:", sec4)

# Print sec5 - all elements from #0 up to and including #15, using the negative number method
sec5 = comboArray[:-16:-1]
print("sec5:", sec5)

# Print sec6 - from #20 every even element to the end
sec6 = comboArray[8::2]
print("sec6:", sec6)

# Print sec7 - from the last element moving forward, every 5th element
sec7 = comboArray[-1::-5]
print("sec7:", sec7)







arr1 = numpy.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
                 [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
                 [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])
arr2 = numpy.array([[17.0, 70.0, 10.7]])
# Perform the addition operation using broadcasting
add_result = arr1 + arr2

# Perform the division operation using broadcasting
div_result = arr1 / arr2

# Perform the multiplication operation using broadcasting
mult_result = arr1 * arr2

# Print the results
print("Addition result:\n", add_result)
print("Division result:\n", div_result)
print("Multiplication result:\n", mult_result)

sub_result = numpy.subtract(arr1, arr2)

# Print the result
print("Subtraction result:\n", sub_result)


#Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.


divisible_by_3 = comboArray[comboArray % 3 == 0]
print("data2 elements divisible_by_2 ...", divisible_by_3)

import pandas as pd
#Using Series, create a DataFrame that looks like this:
ingre = pd.Series(['flour','milk', 'eggs','spam'], name='Ingredients')
qt = pd.Series([4,1,2,1], name='Quantity')
unit=pd.Series(['cups','cup','large','can'], name='Unit')

df = pd.concat([ingre,qt,unit],axis=1)
print(df)
#Take this data and create a DataFrame named studentData

data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

# pass the dict to the Pandas DataFrame constructor
studentData = pd.DataFrame(data)
print("Purchases DataFrame ...\n", studentData)

#Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

# Using DataFrame.insert() to add a column
studentData.insert(2, "deserts", ['ice cream', 'Cashew Fudge','waffels', 'Carrot Halwa'],True)
print("\nDF with insert as column 2 ...\n", studentData)



#Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['Name', 'address'], inplace = True)

print("\nDF sorting multiple columns ...\n", studentData)


#Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
#saving dataframe to .csv
df
df.to_csv('cows_and_goats.csv')

print (df)

veggies = pd.DataFrame({'Pickles': [12, 20], 'green beans': [22, 19]}, index=['Year 1', 'Year 2'])

veggies.to_csv('veggies.csv')

veggies = pd.read_csv("veggies.csv")

veggies.loc[1, 'Pickles'] = "88"
print(veggies.to_string())

veggies.to_csv("veggies2.csv",)