
### 1.What does Pandas stand for?
>Panel Data” and “Python Data Analysis”
### 2.What are the 2 collections used in Pandas?
>Series and dqtq frame
### 3.Name 4 things Pandas can do for us.
>load, manipulate, prepare, model, and analyze data
### 4.To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
>Set the inplace parameter to True.
### 5.What is a CSV
>(comma separated files)CSV files contains plain text and is a well know format that can be read by everyone including Pandas.
### 6.When cleaning data what values do we not like in our data?
>Null

In [12]:
#Concatenate these 3 arrays into a new array named 'newArray'...

import numpy
newArray = numpy.concatenate(([[25, 16]], [[11, 2], [13, 4]], [[7, 81], [5, 6], [11, 12]]))

#concatenate the arrays

print (newArray)

#Sort 'newArray' in order into 'sortedArray'

asortedArray = numpy.sort(newArray) #axis=0)

print ("\n2:Sort 'newArray' in order into 'sortedArray'\n",asortedArray)

#Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = newArray.reshape(2, 3, 2)
print("\n reshaping bArray ...\n", reshapedArray)

#Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.


a, b, = reshapedArray

print("a = ", a + b)










[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

2:Sort 'newArray' in order into 'sortedArray'
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

 reshaping bArray ...
 [[[25 16]
  [11  2]
  [13  4]]

 [[ 7 81]
  [ 5  6]
  [11 12]]]
a =  [[32 97]
 [16  8]
 [24 16]]


In [19]:
#define arrays 
one = [10, 11, 12, 13, 14, 15, 16, 17]
two = [20, 21, 22, 23, 24, 25, 26, 27]
three = [0, 1, 2, 3, 4, 5, 6, 7]

#combine arrays 

comboArray = numpy.concatenate((one, two, three))
#sort arrays
sortedComboArray = numpy.sort(comboArray)

print("5:Combined and sort the following arrays into one\n",sortedComboArray)


# Print sec1 - the 2nd element
sec1 = sortedComboArray[1]
print("sec1:", sec1)

# Print sec2 - all elements from the 3rd element to the last
sec2 = sortedComboArray[2:]
print("sec2:", sec2)

# Print sec3 - all elements from the 4th to the 14th elements
sec3 = sortedComboArray[3:14]
print("sec3:", sec3)

# Print sec4 - the last 6 elements
sec4 = sortedComboArray[-6:]
print("sec4:", sec4)

# Print sec5 - all elements from #0 up to and including #15, using the negative number method
sec5 = sortedComboArray[:-10]
print("sec5:", sec5)

# Print sec6 - from #20 every even element to the end
sec6 = sortedComboArray[16::2]
print("sec6:", sec6)

# Print sec7 - from the last element moving forward, every 5th element
sec7 = sortedComboArray[-1::-5]
print("sec7:", sec7)







arr1 = numpy.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
                 [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
                 [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])
arr2 = numpy.array([[17.0, 70.0, 10.7]])
# Perform the addition operation using broadcasting
add_result = arr1 + arr2

# Perform the division operation using broadcasting
div_result = arr1 / arr2

# Perform the multiplication operation using broadcasting
mult_result = arr1 * arr2

# Print the results
print("Addition result:\n", add_result)
print("Division result:\n", div_result)
print("Multiplication result:\n", mult_result)

sub_result = numpy.subtract(arr1, arr2)

# Print the result
print("Subtraction result:\n", sub_result)


#Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.


divisible_by_3 = comboArray[comboArray % 3 == 0]
print("data2 elements divisible_by_2 ...", divisible_by_3)

import pandas as pd
#Using Series, create a DataFrame that looks like this:
ingre = pd.Series(['flour','milk', 'eggs','spam'], name='Ingredients')
qt = pd.Series([4,1,2,1], name='Quantity')
unit=pd.Series(['cups','cup','large','can'], name='Unit')

df = pd.concat([ingre,qt,unit],axis=1)
print(df)
#Take this data and create a DataFrame named studentData

data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

# pass the dict to the Pandas DataFrame constructor
studentData = pd.DataFrame(data)
print("Purchases DataFrame ...\n", studentData)

#Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

# Using DataFrame.insert() to add a column
studentData.insert(2, "deserts", ['ice cream', 'Cashew Fudge','waffels', 'Carrot Halwa'],True)
print("\nDF with insert as column 2 ...\n", studentData)



#Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['Name', 'address'], inplace = True)

print("\nDF sorting multiple columns ...\n", studentData)


#Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
#saving dataframe to .csv
df
df.to_csv('cows_and_goats.csv')

print (df)

veggies = pd.DataFrame({'Pickles': [12, 20], 'green beans': [22, 19]}, index=['Year 1', 'Year 2'])

veggies.to_csv('veggies.csv')

veggies = pd.read_csv("veggies.csv")

veggies.loc[1, 'Pickles'] = "88"
print(veggies.to_string())

veggies.to_csv("veggies2.csv",)

5:Combined and sort the following arrays into one
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [ 3  4  5  6  7 10 11 12 13 14 15]
sec4: [22 23 24 25 26 27]
sec5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
sec6: [20 22 24 26]
sec7: [27 22 15 10  3]
Addition result:
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]
Division result:
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]
Multiplication result:
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+0